return {
  {
    "mason-org/mason-lspconfig.nvim",
    version = "^1.0.0",
    opts = {
      ensure_installed = {
        "astro",
        "bashls",
        "biome",
        "eslint",
        "html",
        "jsonls",
        "kotlin_language_server",
        "lemminx",
        "marksman",
        "prismals",
        "pyright",
        "nil_ls",
        "sqlls",
        "stylelint_lsp",
        "lua_ls",
        "taplo",
        "texlab",
        "vtsls",
        "yamlls",
      },
    },
  },
  {
    "mason-org/mason.nvim",
    version = "^1.0.0",
    opts = {
      ensure_installed = {
        "codelldb",
        "biome",
        "dart-debug-adapter",
        "eslint_d",
        "luacheck",
        "prettier",
        "prettierd",
        "ruff",
        "shellcheck",
        "shfmt",
        "sqlfluff",
        "stylelint",
        "stylua",
        "xmlformatter",
      },
    },
  },
}
