return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "c",
      "css",
      "diff",
      "html",
      "java",
      "javascript",
      "json",
      "jsdoc",
      "kotlin",
      -- "latex",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "nix",
      "printf",
      "python",
      "query",
      "regex",
      "rust",
      -- "swift",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
    highlight = { enable = true, disable = { "dart" } },
  },
}
