return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "astro",
      "bash",
      "css",
      "dart",
      "html",
      "java",
      "javascript",
      "json",
      "kotlin",
      "latex",
      "lua",
      "markdown",
      "nix",
      "python",
      "query",
      "rust",
      "swift",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "yaml",
    },
  },
}
